
import { Language } from '../types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  English: {
    // Nav
    navSchedule: "Schedule",
    navLifestyle: "Lifestyle",
    navClock: "Clock",
    navTimer: "Timer",
    navHistory: "History",
    
    // Common
    settingsTitle: "System Preferences",
    languageLabel: "System Language",
    themeLabel: "Theme Palette",
    save: "Save",
    cancel: "Cancel",
    reset: "Reset",
    start: "Start",
    pause: "Pause",
    delete: "Delete",
    done: "Done",
    processing: "Processing...",
    
    // Notifications
    scheduledPrefix: "Scheduled",
    
    // Clock
    addClock: "Add Clock",
    cityNamePlaceholder: "Display Name (e.g. Paris)",
    confirmDeleteClock: "Are you sure you want to delete this clock?",
    resetClocks: "Reset Clocks",
    
    // Timer
    stopwatch: "Stopwatch",
    timer: "Timer",
    resetTimer: "Reset Config",
    
    // Scheduler
    butlerConsole: "Butler Console",
    liveItinerary: "Live Itinerary",
    resetProtocol: "Reset Protocol",
    resetConfirm: "Are you sure you want to reset the current schedule and chat history? This cannot be undone.",
    noTasks: "No tasks scheduled yet.",
    typePrompt: "Type in the console to add events.",
    inputPlaceholder: "E.g., 'Add a deep work session at 10 AM'",
    
    // Profile
    profileTitle: "User Identity Profile",
    nameLabel: "Name",
    namePlaceholder: "How should I address you?",
    professionLabel: "Profession",
    professionPlaceholder: "e.g. Software Engineer",
    mbtiLabel: "MBTI Type",
    initProtocol: "Initialize Protocol",
    
    // Lifestyle
    clothingTab: "Clothing & Weather",
    dietTab: "Dietary Protocol",
    satelliteTitle: "Satellite Atmospheric Analysis",
    noData: "No data acquired",
    acquireData: "Acquire Satellite Data",
    refreshData: "Refresh Data",
    styleConfig: "Style Configuration",
    styleLabel: "Selected Aesthetic",
    recommendBtn: "Analyze & Recommend",
    dietTitle: "Nutritional Optimization Protocol",
    dietAnalysis: "Analysis based on profession",
    generateDiet: "Generate Nutritional Protocol",
    regenerateDiet: "Regenerate Protocol",
    serviceUnavailable: "Service unavailable.",
    resetLifestyle: "Reset Data",
    
    // History
    searchPlaceholder: "Search archives (date, task, rationale)...",
    noRecords: "No historical records found matching your query.",
    recordPrefix: "Record",
  },
  
  Chinese: {
    navSchedule: "日程",
    navLifestyle: "生活方式",
    navClock: "世界时钟",
    navTimer: "计时器",
    navHistory: "历史记录",
    settingsTitle: "系统偏好设置",
    languageLabel: "系统语言",
    themeLabel: "主题色调",
    save: "保存",
    cancel: "取消",
    reset: "重置",
    start: "开始",
    pause: "暂停",
    delete: "删除",
    done: "完成",
    processing: "处理中...",
    scheduledPrefix: "日程提醒",
    addClock: "添加时钟",
    cityNamePlaceholder: "显示名称 (如: 北京)",
    confirmDeleteClock: "确定要删除这个时钟吗？",
    resetClocks: "重置时钟",
    stopwatch: "秒表",
    timer: "倒计时",
    resetTimer: "重置配置",
    butlerConsole: "管家控制台",
    liveItinerary: "实时日程表",
    resetProtocol: "重置协议",
    resetConfirm: "您确定要重置当前日程和聊天记录吗？此操作无法撤销。",
    noTasks: "暂无预定任务。",
    typePrompt: "在控制台中输入以添加事项。",
    inputPlaceholder: "例如：'上午10点安排深度工作'",
    profileTitle: "用户身份档案",
    nameLabel: "称呼",
    namePlaceholder: "我该如何称呼您？",
    professionLabel: "职业",
    professionPlaceholder: "例如：软件工程师",
    mbtiLabel: "MBTI 类型",
    initProtocol: "初始化协议",
    clothingTab: "着装与天气",
    dietTab: "饮食方案",
    satelliteTitle: "卫星大气分析",
    noData: "未获取数据",
    acquireData: "获取卫星数据",
    refreshData: "刷新数据",
    styleConfig: "风格配置",
    styleLabel: "审美偏好",
    recommendBtn: "分析并推荐",
    dietTitle: "营养优化方案",
    dietAnalysis: "基于职业分析",
    generateDiet: "生成营养方案",
    regenerateDiet: "重新生成方案",
    serviceUnavailable: "服务暂时不可用。",
    resetLifestyle: "重置数据",
    searchPlaceholder: "搜索存档 (日期, 任务, 理由)...",
    noRecords: "未找到匹配的历史记录。",
    recordPrefix: "记录",
  },
  
  Spanish: {
    navSchedule: "Agenda",
    navLifestyle: "Estilo de Vida",
    navClock: "Reloj",
    navTimer: "Temporizador",
    navHistory: "Historial",
    settingsTitle: "Preferencias del Sistema",
    languageLabel: "Idioma del Sistema",
    themeLabel: "Paleta de Temas",
    save: "Guardar",
    cancel: "Cancelar",
    reset: "Reiniciar",
    start: "Iniciar",
    pause: "Pausar",
    delete: "Eliminar",
    done: "Hecho",
    processing: "Procesando...",
    scheduledPrefix: "Programado",
    addClock: "Añadir Reloj",
    cityNamePlaceholder: "Nombre (ej. Madrid)",
    confirmDeleteClock: "¿Está seguro de que desea eliminar este reloj?",
    resetClocks: "Reiniciar Relojes",
    stopwatch: "Cronómetro",
    timer: "Temporizador",
    resetTimer: "Reiniciar Config.",
    butlerConsole: "Consola del Mayordomo",
    liveItinerary: "Itinerario en Vivo",
    resetProtocol: "Restablecer Protocolo",
    resetConfirm: "¿Está seguro de que desea restablecer el horario y el historial de chat? Esto no se puede deshacer.",
    noTasks: "No hay tareas programadas.",
    typePrompt: "Escriba en la consola para añadir eventos.",
    inputPlaceholder: "Ej., 'Añadir sesión de trabajo profundo a las 10 AM'",
    profileTitle: "Perfil de Identidad",
    nameLabel: "Nombre",
    namePlaceholder: "¿Cómo debo dirigirme a usted?",
    professionLabel: "Profesión",
    professionPlaceholder: "ej. Ingeniero de Software",
    mbtiLabel: "Tipo MBTI",
    initProtocol: "Inicializar Protocolo",
    clothingTab: "Ropa y Clima",
    dietTab: "Protocolo Dietético",
    satelliteTitle: "Análisis Atmosférico por Satélite",
    noData: "Datos no adquiridos",
    acquireData: "Adquirir Datos Satelitales",
    refreshData: "Actualizar Datos",
    styleConfig: "Configuración de Estilo",
    styleLabel: "Estética Seleccionada",
    recommendBtn: "Analizar y Recomendar",
    dietTitle: "Protocolo de Optimización Nutricional",
    dietAnalysis: "Análisis basado en profesión",
    generateDiet: "Generar Protocolo Nutricional",
    regenerateDiet: "Regenerar Protocolo",
    serviceUnavailable: "Servicio no disponible.",
    resetLifestyle: "Restablecer Datos",
    searchPlaceholder: "Buscar archivos (fecha, tarea, razón)...",
    noRecords: "No se encontraron registros históricos.",
    recordPrefix: "Registro",
  },
  
  French: {
    navSchedule: "Planning",
    navLifestyle: "Art de Vivre",
    navClock: "Horloge",
    navTimer: "Chronomètre",
    navHistory: "Historique",
    settingsTitle: "Préférences Système",
    languageLabel: "Langue du Système",
    themeLabel: "Palette de Thèmes",
    save: "Enregistrer",
    cancel: "Annuler",
    reset: "Réinitialiser",
    start: "Démarrer",
    pause: "Pause",
    delete: "Supprimer",
    done: "Terminé",
    processing: "Traitement...",
    scheduledPrefix: "Prévu",
    addClock: "Ajouter Horloge",
    cityNamePlaceholder: "Nom (ex. Paris)",
    confirmDeleteClock: "Êtes-vous sûr de vouloir supprimer cette horloge ?",
    resetClocks: "Réinitialiser Horloges",
    stopwatch: "Chronomètre",
    timer: "Minuteur",
    resetTimer: "Réinit. Config",
    butlerConsole: "Console Majordome",
    liveItinerary: "Itinéraire en Direct",
    resetProtocol: "Réinitialiser Protocole",
    resetConfirm: "Êtes-vous sûr de vouloir réinitialiser le planning et l'historique ? Cette action est irréversible.",
    noTasks: "Aucune tâche programmée.",
    typePrompt: "Tapez dans la console pour ajouter des événements.",
    inputPlaceholder: "Ex., 'Ajouter une session de travail à 10h'",
    profileTitle: "Profil d'Identité",
    nameLabel: "Nom",
    namePlaceholder: "Comment dois-je vous appeler ?",
    professionLabel: "Profession",
    professionPlaceholder: "ex. Ingénieur Logiciel",
    mbtiLabel: "Type MBTI",
    initProtocol: "Initialiser Protocole",
    clothingTab: "Tenue & Météo",
    dietTab: "Protocole Diététique",
    satelliteTitle: "Analyse Atmosphérique Satellite",
    noData: "Aucune donnée acquise",
    acquireData: "Acquérir Données Satellite",
    refreshData: "Actualiser Données",
    styleConfig: "Configuration de Style",
    styleLabel: "Esthétique Sélectionnée",
    recommendBtn: "Analyser & Recommander",
    dietTitle: "Protocole d'Optimisation Nutritionnelle",
    dietAnalysis: "Analyse basée sur la profession",
    generateDiet: "Générer Protocole Nutritionnel",
    regenerateDiet: "Régénérer Protocole",
    serviceUnavailable: "Service indisponible.",
    resetLifestyle: "Réinitialiser Données",
    searchPlaceholder: "Rechercher archives (date, tâche, raison)...",
    noRecords: "Aucun enregistrement trouvé.",
    recordPrefix: "Enregistrement",
  },
  
  Russian: {
    navSchedule: "Расписание",
    navLifestyle: "Образ жизни",
    navClock: "Часы",
    navTimer: "Таймер",
    navHistory: "История",
    settingsTitle: "Системные настройки",
    languageLabel: "Язык системы",
    themeLabel: "Цветовая палитра",
    save: "Сохранить",
    cancel: "Отмена",
    reset: "Сброс",
    start: "Старт",
    pause: "Пауза",
    delete: "Удалить",
    done: "Готово",
    processing: "Обработка...",
    scheduledPrefix: "Запланировано",
    addClock: "Добавить часы",
    cityNamePlaceholder: "Название (напр. Москва)",
    confirmDeleteClock: "Вы уверены, что хотите удалить эти часы?",
    resetClocks: "Сброс часов",
    stopwatch: "Секундомер",
    timer: "Таймер",
    resetTimer: "Сброс настр.",
    butlerConsole: "Консоль Дворецкого",
    liveItinerary: "Текущий маршрут",
    resetProtocol: "Сброс протокола",
    resetConfirm: "Вы уверены, что хотите сбросить текущее расписание и историю чата? Это действие необратимо.",
    noTasks: "Задач пока нет.",
    typePrompt: "Введите в консоль для добавления событий.",
    inputPlaceholder: "Напр., 'Добавить сессию глубокой работы в 10:00'",
    profileTitle: "Профиль личности",
    nameLabel: "Имя",
    namePlaceholder: "Как мне к вам обращаться?",
    professionLabel: "Профессия",
    professionPlaceholder: "напр. Инженер-программист",
    mbtiLabel: "Тип MBTI",
    initProtocol: "Инициализировать протокол",
    clothingTab: "Одежда и погода",
    dietTab: "Диетический протокол",
    satelliteTitle: "Спутниковый анализ атмосферы",
    noData: "Данные не получены",
    acquireData: "Получить спутниковые данные",
    refreshData: "Обновить данные",
    styleConfig: "Конфигурация стиля",
    styleLabel: "Выбранная эстетика",
    recommendBtn: "Анализировать и рекомендовать",
    dietTitle: "Протокол оптимизации питания",
    dietAnalysis: "Анализ на основе профессии",
    generateDiet: "Создать протокол питания",
    regenerateDiet: "Создать заново",
    serviceUnavailable: "Сервис недоступен.",
    resetLifestyle: "Сброс данных",
    searchPlaceholder: "Поиск в архивах (дата, задача, причина)...",
    noRecords: "Исторических записей не найдено.",
    recordPrefix: "Запись",
  },
  
  Arabic: {
    navSchedule: "جدول الأعمال",
    navLifestyle: "نمط الحياة",
    navClock: "الساعة",
    navTimer: "المؤقت",
    navHistory: "السجل",
    settingsTitle: "تفضيلات النظام",
    languageLabel: "لغة النظام",
    themeLabel: "لوحة السمات",
    save: "حفظ",
    cancel: "إلغاء",
    reset: "إعادة تعيين",
    start: "بدء",
    pause: "إيقاف مؤقت",
    delete: "حذف",
    done: "تم",
    processing: "جارٍ المعالجة...",
    scheduledPrefix: "مجدول",
    addClock: "إضافة ساعة",
    cityNamePlaceholder: "الاسم المعروض (مثل دبي)",
    confirmDeleteClock: "هل أنت متأكد أنك تريد حذف هذه الساعة؟",
    resetClocks: "إعادة تعيين الساعات",
    stopwatch: "ساعة إيقاف",
    timer: "مؤقت",
    resetTimer: "إعادة ضبط",
    butlerConsole: "وحدة تحكم الخادم",
    liveItinerary: "خط سير العمل المباشر",
    resetProtocol: "إعادة تعيين البروتوكول",
    resetConfirm: "هل أنت متأكد أنك تريد إعادة تعيين الجدول الحالي وسجل الدردشة؟ لا يمكن التراجع عن هذا.",
    noTasks: "لا توجد مهام مجدولة بعد.",
    typePrompt: "اكتب في وحدة التحكم لإضافة أحداث.",
    inputPlaceholder: "مثلاً، 'أضف جلسة عمل عميق في الساعة 10 صباحًا'",
    profileTitle: "ملف تعريف الهوية",
    nameLabel: "الاسم",
    namePlaceholder: "كيف يجب أن أخاطبك؟",
    professionLabel: "المهنة",
    professionPlaceholder: "مثلاً مهندس برمجيات",
    mbtiLabel: "نمط MBTI",
    initProtocol: "بدء البروتوكول",
    clothingTab: "الملابس والطقس",
    dietTab: "البروتوكول الغذائي",
    satelliteTitle: "تحليل الغلاف الجوي عبر الأقمار الصناعية",
    noData: "لم يتم الحصول على بيانات",
    acquireData: "الحصول على بيانات الأقمار الصناعية",
    refreshData: "تحديث البيانات",
    styleConfig: "تكوين الأسلوب",
    styleLabel: "الجمالية المختارة",
    recommendBtn: "تحليل وتوصية",
    dietTitle: "بروتوكول تحسين التغذية",
    dietAnalysis: "تحليل قائم على المهنة",
    generateDiet: "إنشاء البروتوكول الغذائي",
    regenerateDiet: "إعادة إنشاء البروتوكول",
    serviceUnavailable: "الخدمة غير متوفرة.",
    resetLifestyle: "إعادة تعيين البيانات",
    searchPlaceholder: "البحث في الأرشيف (التاريخ، المهمة، السبب)...",
    noRecords: "لم يتم العثور على سجلات تاريخية.",
    recordPrefix: "سجل",
  }
};
